// ACTION TYPE CONSTANTS

export const RESET_STATE_TO_DEFAULTS = 'RESET_STATE_TO_DEFAULTS';

export const CREATE_DOCUMENTS_IN_DBS_FOR_FIRST_TIME = 'CREATE_DOCUMENTS_IN_DBS_FOR_FIRST_TIME';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const LOADING_APP = 'LOADING_APP';
export const LOADING_BACKEND_ERROR = 'LOADING_BACKEND_ERROR';
export const LOADING_BACKEND_UPDATE = 'LOADING_BACKEND_UPDATE';

export const LOAD_FROM_ALL_DBS_STARTED = 'LOAD_FROM_ALL_DBS_STARTED';
export const LOAD_FROM_ALL_DBS_FINISHED = 'LOAD_FROM_ALL_DBS_FINISHED';
export const LOAD_FROM_USERS_DB = 'LOAD_FROM_USERS_DB';
export const LOAD_FROM_MISCELLANEOUS_DB = 'LOAD_FROM_MISCELLANEOUS_DB';
export const LOAD_FROM_ADMIN_FACTORS_DB = 'LOAD_FROM_ADMIN_FACTORS_DB';
export const LOAD_FROM_TEAMS_DB = 'LOAD_FROM_TEAMS_DB';
export const LOAD_FROM_FIXTURES_DB = 'LOAD_FROM_FIXTURES_DB';
export const LOAD_FROM_LEAGUE_TABLE_DB = 'LOAD_FROM_LEAGUE_TABLE_DB';

export const MERGE_DOCUMENT_IDS_FROM_TEAMS_DB = 'MERGE_DOCUMENT_IDS_FROM_TEAMS_DB';
export const MERGE_DOCUMENT_IDS_FROM_FIXTURES_DB = 'MERGE_DOCUMENT_IDS_FROM_FIXTURES_DB';
export const MERGE_DOCUMENT_IDS_FROM_LEAGUE_TABLE_DB = 'MERGE_DOCUMENT_IDS_FROM_LEAGUE_TABLE_DB';

export const ADMIN_FACTORS_SAVE_CHANGES = 'ADMIN_FACTORS_SAVE_CHANGES';
export const ADMIN_TEAMS_SAVE_CHANGES = 'ADMIN_TEAMS_SAVE_CHANGES';

export const LATEST_FIXTURES_UPDATE_AFTER_RESULTS = 'LATEST_FIXTURES_UPDATE_AFTER_RESULTS';
export const LATEST_FIXTURES_SEASON_HAS_FINISHED = 'LATEST_FIXTURES_SEASON_HAS_FINISHED';

export const UPDATE_FIXTURES_IN_STORE_AFTER_RESULTS = 'UPDATE_FIXTURES_IN_STORE_AFTER_RESULTS';
export const UPDATE_LEAGUE_TABLE_IN_STORE_AFTER_RESULTS = 'UPDATE_LEAGUE_TABLE_IN_STORE_AFTER_RESULTS';

export const UPDATE_MISCELLANEOUS_PROPERTY = 'UPDATE_MISCELLANEOUS_PROPERTY';
